# This is a basic workflow to help you get started with Actions

name: Solhint Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
      - name: Run yarn install
        run: yarn install
      - name: Run lint
        run: yarn lint
